### ISSUE TITLE
Multi-slit data?

### ISSUE THREAD

**Issue by astronomeara** [pyigm/igmspec#13]
Suppose, as eventually in the case of HS1700 for example, we have a set of multi-slit data from MOSFIRE, LRIS, DEIMOS, etc near a quasar from our surveys.  Should we incorporate those spectra into igmspec?  It could facilitate fast searches for galaxies near certain redshifts in the qso spectrum.  May be too much work for too specific a return.

**Comment by jhennawi** [comment]
Yeah, I think a galaxy spectra database is a big undertaken, and should perhaps be a separate database. The other option is to just load the kitchen sink into the database, but then you need to accommodate a million SDSS galaxy spectra.

**Comment by profxj** [comment]
Stay tuned for galaxyspec.
Coming to you by the end of 2016.
