### ISSUE TITLE
Version history

### ISSUE THREAD

**Issue by profxj** [pyigm/igmspec#19]
Should the code be written to:
  a.  Enable the "exact" reproduction of every version release of the DB?
  b.  Build on pervious versions or start over building from scratch?

**Comment by profxj** [comment]
Note that Option (a) would probably mean saving a full copy of the 
underlying DB of each version of the igmspec DB  
[Could grow to Tb levels]

**Comment by jhennawi** [comment]
My suggestion is that you just somehow archive versions of the database somewhere, such that people can re-create previous versions if they have to. But that the standard database is only the latest version.

**Comment by profxj** [comment]
We will definitely do this.  And I now realize I can achieve the software side
of things by tagging.  Only thing that won’t be ‘right’ is that the uber-database
(which will sit on my machine) will evolve and I won’t save all the bits and pieces.

> On Jun 28, 2016, at 3:25 AM, jhennawi <notifications@github.com> wrote:
> 
> My suggestion is that you just somehow archive versions of the database somewhere, such that people can re-create previous versions if they have to. But that the standard database is only the latest version.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub <https://github.com/pyigm/igmspec/issues/19#issuecomment-229011200>, or mute the thread <https://github.com/notifications/unsubscribe/AD0BjdJF5CAkUPa9sNv6TvmAK5CL38vPks5qQPaDgaJpZM4I9OJ4>.
> 
> !DSPAM:826,577250962001060417183!

----------------------------------------------
J. Xavier Prochaska
UCO/Lick Observatory
1156 High St.
UC Santa Cruz
Santa Cruz, CA 95064

http://www.ucolick.org/~xavier/
http://imps.ucolick.org/
http://www.qpqsurvey.org/
http://k1dm3.ucolick.org/
http://www.ucolick.org/~xavier/IDL/index.html
https://github.com/pyigm/pyigm
https://github.com/linetools/linetools

831-459-2135 (Direct)
831-459-2991 (UCO/Lick Main)
831-459-5244 (Fax)

**Comment by profxj** [comment]
Tagged v1.0
