### ISSUE TITLE
Simple Usage example

### ISSUE THREAD

**Issue by ninoc** [pyigm/igmspec#25]
Hi all,
I think there is a missing line in the Simple_Usage.ipynb:

I added this to the initial inputs: 
from astropy import units as u

Also, when I grab the example spectra there is "sig" keyword missing.
I guess the sigma spectrum is missing?

I ran the cell:
# Grab spectra
J0812spec, meta = igmsp.grab_spec('KODIAQ_DR1', ids0812)

and got this in return:
Staged 1 spectra totalling 0.0032 Gb
Loaded spectra
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-11-733a8405b743> in <module>()
      1 # Grab spectra
----> 2 J0812spec, meta = igmsp.grab_spec('KODIAQ_DR1', ids0812)

/anaconda/anaconda/envs/astroconda/lib/python2.7/site-packages/igmspec-0.0.dev0-py2.7.egg/igmspec/interface_db.pyc in grab_spec(self, survey, IGM_IDs, verbose, **kwargs)
    195             return
    196         # Generate XSpectrum1D
--> 197         spec = XSpectrum1D(data['wave'], data['flux'], sig=data['sig'], masking='edges')
    198         # Return
    199         return spec, self.meta

TypeError: __init__() got an unexpected keyword argument 'sig'

Nino

**Comment by profxj** [comment]
I agree with the astropy issue and have edited the Notebook.
I think the other issue is your fault.  Am guessing your linetools
is out of date.

**Comment by profxj** [comment]
closing
