### ISSUE TITLE
"proprietary" version

### ISSUE THREAD

**Issue by astronomeara** [pyigm/igmspec#30]
Any interest in making a proprietary version of the DB so that we can include "in-work" data (e.g. WFC3 pairs, operation headshot, etc) spectra.  perhaps a call to get_igmspec that requires a password (not sure how one would do that....)

**Comment by geordie666** [comment]
One potential method would be to have such a DB sitting off git on
someone's private server, with a (user/passworded) wget command to recover
it.

**Comment by profxj** [comment]
Enabled by PR #37
