### ISSUE TITLE
Continuua

### ISSUE THREAD

**Issue by profxj** [pyigm/igmspec#6]
Consider adding continua, e.g.
  SDSS-DR7  (mine or Gunagtung's)
  BOSS (QPQ)
  GGG (from LLS analysis?)

**Comment by astronomeara** [comment]
All continua from KODIAQ are preserved in redux file structure, in case you wish to somehow bring those into the mix.

**Comment by profxj** [comment]
You tell me.  Are these useful to the community?

----------------------------------------------
J. Xavier Prochaska
UCO/Lick Observatory
1156 High St.
UC Santa Cruz
Santa Cruz, CA 95064

http://www.ucolick.org/~xavier/ <http://www.ucolick.org/~xavier/>
http://imps.ucolick.org/ <http://imps.ucolick.org/>
http://www.qpqsurvey.org/ <http://www.qpqsurvey.org/>
http://k1dm3.ucolick.org/ <http://k1dm3.ucolick.org/>
http://www.ucolick.org/~xavier/IDL/index.html <http://www.ucolick.org/~xavier/IDL/index.html>
https://github.com/profxj/xastropy <https://github.com/profxj/xastropy>

831-459-2135 (Direct)
831-459-2991 (UCO/Lick Main)
831-459-5244 (Fax)

**Comment by jhennawi** [comment]
KGs released his continua for a large part of BOSS DR something.

**Comment by astronomeara** [comment]
Continua certainly useful to community for rather high SNR data and ppl looking for weak features.  Nightmare integrating it into igmspec, I fear.

**Comment by profxj** [comment]
Never fear; continua are on the way.

**Comment by profxj** [comment]
Now in there for BOSS
