### ISSUE TITLE
Fix GGG DATE-OBS

### ISSUE THREAD

**Issue by profxj** [pyigm/igmspec#8]
SMJD is for SDSS

For GMOS either refer to the FITS header of the spectrum or the paper. 
Several targets got reobserved, so the FITS header is not always very informative.

**Comment by jhennawi** [comment]
I think the observation date needs to be like that of the co-add or something, and the headers should log the files that got combined into one. I don't see why one would need the headers of each of the individual frames that got co-added into one.

**Comment by profxj** [comment]
Fixed by using the XIDL output.  Not sure
if there was any coadding over multiple nights but that
is not being incuded.
